name: action

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: configure
      working-directory: ./test 
      run: cmake -B ${{github.workspace}}/build
      
    - name: build
      working-directory: ./test
      run: cmake --build ${{github.workspace}}/build

    - name: run
      working-directory: ./test
      run: ${{github.workspace}}/build/test