name: action

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: change dir
      run: cd test/

    - name: configure
      run: cmake -B ${{github.workspace}}/build
      
    - name: build
      run: cmake --build ${{github.workspace}}/build

    - name: run
      run: ${{github.workspace}}/build/test